name: Alt-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with: { python-version: 3.9 }
      - name: Cache python & requirements
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: python|${{ env.pythonLocation }}|${{ hashFiles('requirements.txt') }}
      - name: Cache pre-commit hooks
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Run pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Run tests
        run: pytest
