name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        echo "Install python dependencies"
        python3 -m pip install --upgrade pip
        python3 -m pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo $PYTHONPATH
    - name: Python linter 
      run: pylint `ls -R|grep .py$|xargs`
    - name: Test simulator
      run: python3 -m unittest simulator/test_*
